all:
  hosts:
    cp1:
      ansible_host: 192.168.1.20
      ip: 192.168.1.20
      access_ip: 192.168.1.20
    wk1:
      ansible_host: 192.168.1.30
      ip: 192.168.1.30
      access_ip: 192.168.1.30
    wk2:
      ansible_host: 192.168.1.40
      ip: 192.168.1.40
      access_ip: 192.168.1.40
  children:
    kube_control_plane:
      hosts:
        cp1:
    kube_node:
      hosts:
        cp1:
        wk1:
        wk2:
    etcd:
      hosts:
        cp1:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
