secrets:
  - name: "pihole-password"
    namespace: "default"
    data:
      EXTERNAL_DNS_PIHOLE_PASSWORD: ""
  - name: "operator-oauth"
    namespace: "tailscale"
    data:
      client_id: ""
      client_secret: ""
  