---
- name: Update Gitea
  hosts: git_servers
  become: yes
  tasks:
    - name: Update packages
      apt:
        update_cache: yes
        upgrade: yes
        autoremove: yes

    - name: Stop Gitea with Docker Compose
      command: docker compose down --remove-orphans
      args:
        chdir: "{{ gitea_data_dir }}"

    - name: Include Gitea docker compose task
      include_tasks: install_docker_compose_gitea.yml

    - name: Start Gitea with Docker Compose
      command: docker compose up -d
      args:
        chdir: "{{ gitea_data_dir }}"
