repoURL: 'https://stefanprodan.github.io/podinfo'
chart_version: 6.7.0
namespace: "podinfo"
chart_values:
  ingress:
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod # name of the issuer we defined before
      external-dns.alpha.kubernetes.io/hostname: podinfo.tailf3f14.ts.net
      kubernetes.io/tls-acme: "true"
    hosts:
      - host: podinfo.tailf3f14.ts.net
        paths:
          - path: /
            pathType: ImplementationSpecific
      tls:
        - secretName: podinfo.tailf3f14.ts.net
          hosts:
            - podinfo.tailf3f14.ts.net