- name: Recursively delete /tmp/operators    directory
  file:
    path: /tmp/operators
    state: absent

- name: Recursively delete /tmp/applications directory
  file:
    path: /tmp/applications
    state: absent

- name: Copy tmp directory
  copy:
    src: ./tmp/
    dest: /tmp
    mode: '0644'
    directory_mode: '0755'