- name: Ensure .tmp directory exists
  file:
    path: ./tmp
    state: directory

- name: Include variables for each chart
  include_vars:
    file: "group_vars/{{ item.name }}.yaml"
    name: "{{ item.name }}_vars"
  loop: "{{ charts }}"
  loop_control:
    label: "{{ item.name }}"

- name: Debug loaded variables
  debug:
    msg: "{{ hostvars['localhost'][item.name ~ '_vars'] }}"
  loop: "{{ charts }}"
  loop_control:
    label: "{{ item.name }}"

- name: Render the Jinja2 template for each chart
  template:
    src: templates/_argocd_application.yaml.j2
    dest: "./tmp/{{ item.name }}_application.yaml"
  loop: "{{ charts }}"
  vars:
    chart_name: "{{ item.name }}"
    repoURL: "{{ hostvars['localhost'][item.name ~ '_vars'].repoURL }}"
    chart_version: "{{ hostvars['localhost'][item.name ~ '_vars'].chart_version }}"
    namespace: "{{ hostvars['localhost'][item.name ~ '_vars'].namespace }}"
    chart_values: "{{ hostvars['localhost'][item.name ~ '_vars'].chart_values }}"
