all:
  hosts:
    cp1-k8s-proxmox:
      ansible_host: cp1-k8s-proxmox
      ip: 192.168.1.20
      access_ip: 192.168.1.20
    wk1-k8s-proxmox:
      ansible_host: wk1-k8s-proxmox
      ip: 192.168.1.30
      access_ip: 192.168.1.30
  children:
    kube_control_plane:
      hosts:
        cp1-k8s-proxmox:
    kube_node:
      hosts:
        cp1-k8s-proxmox:
        wk1-k8s-proxmox:
    etcd:
      hosts:
        cp1-k8s-proxmox:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
