chart_name: "kube-prometheus-stack"
repoURL: 'https://prometheus-community.github.io/helm-charts'
chart_version: 63.1.0
namespace: "monitoring"
chart_values: 
  grafana:
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod 
        external-dns.alpha.kubernetes.io/hostname: grafana.k8s.olmden.si
        kubernetes.io/tls-acme: "true"
      hosts:
        - grafana.k8s.olmden.si
      tls:
        - secretName: grafana.k8s.olmden.si
          hosts:
            - grafana.k8s.olmden.si