- name: Delete local directory
  delegate_to: localhost
  file:
    path: "{{ local_dir }}"
    state: absent

- name: Delete remote directory
  file:
    path: "{{ remote_dir }}"
    state: absent

- name: Recreate local directory
  delegate_to: localhost
  file:
    path: "{{ local_dir }}"
    state: directory


