- hosts: localhost
  gather_facts: no
  vars_files:
    - vars.yml
  tasks:
    - name: Recursively delete /tmp/applications directory
      file:
        path: ./tmp/
        state: absent

    - name: Install Operators
      include_tasks: playbooks/template_and_apply.yaml
      when: "'operators' in play"
      vars:
        dir: "operators"
        charts: "{{ installation_type | selectattr('operators', 'defined') | map(attribute='operators') | first }}"

    - name: Install Applications
      include_tasks: playbooks/template_and_apply.yaml
      when: "'applications' in play"
      vars:
        dir: "applications"
        charts: "{{ installation_type | selectattr('applications', 'defined') | map(attribute='applications') | first }}"

- hosts: k8s-nodes
  gather_facts: no
  vars_files:
    - vars.yml
  tasks:

    - name: Handle /tmp directory
      include_tasks: playbooks/handle_dir.yaml

    - name: Find all YAML files in /tmp/operators
      command: "find /tmp/operators -name '*.yaml'"
      when: "'operators' in play"
      become: true
      register: operators_files

    - name: Apply Kubernetes manifests
      when: "'operators' in play"
      command: "sudo kubectl apply -f {{ item }}"
      become: true
      loop: "{{ operators_files.stdout_lines }}"

    - name: Find all YAML files in /tmp/applications
      command: "find /tmp/applications -name '*.yaml'"
      when: "'applications' in play"
      become: true
      register: applications_files

    - name: Apply Kubernetes manifests
      when: "'applications' in play"
      command: "sudo kubectl apply -f {{ item }}"
      become: true
      loop: "{{ applications_files.stdout_lines }}"
