apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://nextcloud.github.io/helm/'
    targetRevision: 5.5.6
    helm:
      values: |-
  
        service:
          annotations:
            tailscale.com/expose: "true"
    chart: nextcloud
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
