apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://pkgs.tailscale.com/helmcharts'
    targetRevision: 1.72.1
    helm:
      values: >-
        oauth:
          clientId: X
          clientSecret: X
    chart: tailscale-operator
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: tailscale
  syncPolicy:
    syncOptions:
      - CreateNamespace=true